// This file is auto-generated by @hey-api/openapi-ts

export type UpdateEmailRequestDto = {
    /**
     * The new email address
     */
    email: string;
};

export type RegisterRequestDto = {
    /**
     * The email address
     */
    email: string;
    /**
     * The password
     */
    password: string;
};

export type AddTodoRequestDto = {
    /**
     * The title of the todo
     */
    title: string;
};

export type TodoDto = {
    /**
     * The unique identifier of the todo
     */
    id: string;
    /**
     * The title of the todo
     */
    title: string;
    /**
     * The completion status of the todo
     */
    completed: boolean;
    /**
     * The creation timestamp of the todo
     */
    createdAt: number;
    /**
     * The last update timestamp of the todo
     */
    updatedAt?: number;
};

export type GetAllTodosResponseDto = {
    /**
     * Array of todo items
     */
    todos: Array<TodoDto>;
};

export type ModifyTodoTitleRequestDto = {
    /**
     * The unique identifier of the todo
     */
    id: string;
    /**
     * The new title of the todo
     */
    title: string;
};

export type OnTodoRequest = {
    [key: string]: unknown;
};

export type AuthControllerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerResponses = {
    201: unknown;
};

export type AuthControllerUpdateEmailData = {
    body: UpdateEmailRequestDto;
    path?: never;
    query?: never;
    url: '/auth/updateEmail';
};

export type AuthControllerUpdateEmailResponses = {
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterRequestDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterResponses = {
    201: unknown;
};

export type TodoControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todos';
};

export type TodoControllerGetAllResponses = {
    /**
     * Returns all todos
     */
    200: GetAllTodosResponseDto;
};

export type TodoControllerGetAllResponse = TodoControllerGetAllResponses[keyof TodoControllerGetAllResponses];

export type TodoControllerAddTodoData = {
    body: AddTodoRequestDto;
    path?: never;
    query?: never;
    url: '/todos';
};

export type TodoControllerAddTodoErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type TodoControllerAddTodoResponses = {
    /**
     * Todo created successfully
     */
    201: unknown;
};

export type TodoControllerCompleteTodoData = {
    body?: never;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/todos/{id}/complete';
};

export type TodoControllerCompleteTodoErrors = {
    /**
     * Invalid todo ID
     */
    400: unknown;
    /**
     * Todo not found
     */
    404: unknown;
};

export type TodoControllerCompleteTodoResponses = {
    /**
     * Todo marked as completed
     */
    204: void;
};

export type TodoControllerCompleteTodoResponse = TodoControllerCompleteTodoResponses[keyof TodoControllerCompleteTodoResponses];

export type TodoControllerUncompleteTodoData = {
    body?: never;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/todos/{id}/uncomplete';
};

export type TodoControllerUncompleteTodoErrors = {
    /**
     * Invalid todo ID
     */
    400: unknown;
    /**
     * Todo not found
     */
    404: unknown;
};

export type TodoControllerUncompleteTodoResponses = {
    /**
     * Todo marked as uncompleted
     */
    204: void;
};

export type TodoControllerUncompleteTodoResponse = TodoControllerUncompleteTodoResponses[keyof TodoControllerUncompleteTodoResponses];

export type TodoControllerModifyTitleData = {
    body: ModifyTodoTitleRequestDto;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/todos/{id}/title';
};

export type TodoControllerModifyTitleErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Todo not found
     */
    404: unknown;
};

export type TodoControllerModifyTitleResponses = {
    /**
     * Todo title updated
     */
    204: void;
};

export type TodoControllerModifyTitleResponse = TodoControllerModifyTitleResponses[keyof TodoControllerModifyTitleResponses];

export type TodoControllerDeleteTodoData = {
    body?: never;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodoControllerDeleteTodoErrors = {
    /**
     * Invalid todo ID
     */
    400: unknown;
    /**
     * Todo not found
     */
    404: unknown;
};

export type TodoControllerDeleteTodoResponses = {
    /**
     * Todo deleted
     */
    204: void;
};

export type TodoControllerDeleteTodoResponse = TodoControllerDeleteTodoResponses[keyof TodoControllerDeleteTodoResponses];

export type TodoSseControllerStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sse/todos/stream';
};

export type TodoSseControllerStreamResponses = {
    200: unknown;
};

export type TodoSseControllerOnData = {
    body: OnTodoRequest;
    path?: never;
    query?: never;
    url: '/sse/todos/On';
};

export type TodoSseControllerOnResponses = {
    201: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};