// This file is auto-generated by @hey-api/openapi-ts

export type AddTodoRequestDto = {
    /**
     * The title of the todo
     */
    title: string;
};

export type TodoDto = {
    /**
     * The unique identifier of the todo
     */
    id: string;
    /**
     * The title of the todo
     */
    title: string;
    /**
     * The completion status of the todo
     */
    completed: boolean;
    /**
     * The creation timestamp of the todo
     */
    createdAt: number;
    /**
     * The last update timestamp of the todo
     */
    updatedAt?: number;
};

export type GetAllTodosResponseDto = {
    /**
     * Array of todo items
     */
    todos: Array<TodoDto>;
};

export type ModifyTodoTitleRequestDto = {
    /**
     * The unique identifier of the todo
     */
    id: string;
    /**
     * The new title of the todo
     */
    title: string;
};

export type TodoSubscriptionDto = {
    subscriberId: string;
    events: Array<string>;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeResponses = {
    200: unknown;
};

export type TodoControllerGetAllData = {
    body?: never;
    path?: never;
    query: {
        limit: number;
        offset: number;
    };
    url: '/todos';
};

export type TodoControllerGetAllResponses = {
    /**
     * Returns all todos
     */
    200: GetAllTodosResponseDto;
};

export type TodoControllerGetAllResponse = TodoControllerGetAllResponses[keyof TodoControllerGetAllResponses];

export type TodoControllerAddTodoData = {
    body: AddTodoRequestDto;
    path?: never;
    query?: never;
    url: '/todos';
};

export type TodoControllerAddTodoErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type TodoControllerAddTodoResponses = {
    /**
     * Todo created successfully
     */
    201: unknown;
};

export type TodoControllerCompleteTodoData = {
    body?: never;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/todos/{id}/complete';
};

export type TodoControllerCompleteTodoErrors = {
    /**
     * Invalid todo ID
     */
    400: unknown;
    /**
     * Todo not found
     */
    404: unknown;
};

export type TodoControllerCompleteTodoResponses = {
    /**
     * Todo marked as completed
     */
    204: void;
};

export type TodoControllerCompleteTodoResponse = TodoControllerCompleteTodoResponses[keyof TodoControllerCompleteTodoResponses];

export type TodoControllerUncompleteTodoData = {
    body?: never;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/todos/{id}/uncomplete';
};

export type TodoControllerUncompleteTodoErrors = {
    /**
     * Invalid todo ID
     */
    400: unknown;
    /**
     * Todo not found
     */
    404: unknown;
};

export type TodoControllerUncompleteTodoResponses = {
    /**
     * Todo marked as uncompleted
     */
    204: void;
};

export type TodoControllerUncompleteTodoResponse = TodoControllerUncompleteTodoResponses[keyof TodoControllerUncompleteTodoResponses];

export type TodoControllerModifyTitleData = {
    body: ModifyTodoTitleRequestDto;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/todos/{id}/title';
};

export type TodoControllerModifyTitleErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Todo not found
     */
    404: unknown;
};

export type TodoControllerModifyTitleResponses = {
    /**
     * Todo title updated
     */
    204: void;
};

export type TodoControllerModifyTitleResponse = TodoControllerModifyTitleResponses[keyof TodoControllerModifyTitleResponses];

export type TodoControllerDeleteTodoData = {
    body?: never;
    path: {
        /**
         * Todo ID
         */
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodoControllerDeleteTodoErrors = {
    /**
     * Invalid todo ID
     */
    400: unknown;
    /**
     * Todo not found
     */
    404: unknown;
};

export type TodoControllerDeleteTodoResponses = {
    /**
     * Todo deleted
     */
    204: void;
};

export type TodoControllerDeleteTodoResponse = TodoControllerDeleteTodoResponses[keyof TodoControllerDeleteTodoResponses];

export type TodoSseControllerStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sse/todos/stream';
};

export type TodoSseControllerStreamResponses = {
    200: unknown;
};

export type TodoSseControllerSubscribeData = {
    body: TodoSubscriptionDto;
    path?: never;
    query?: never;
    url: '/sse/todos/subscriptions';
};

export type TodoSseControllerSubscribeResponses = {
    201: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};