apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: bitloops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_IP
              value: 0.0.0.0
            - name: NATS_HOST
              value: bl-nats
            - name: PG_HOST
              value: bl-postgres
            - name: PG_DATABASE
              value: bitloops
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: secret-bl-postgres-secret
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-bl-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-bl-postgres-secret
                  key: JWT_SECRET
          ports:
            - containerPort: 8080
