apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: bitloops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: todo-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
