apiVersion: v1
kind: Secret
metadata:
  name: bl-keycloak-secret
  namespace: bitloops
stringData:
  KEYCLOAK_DB_PASSWORD: replace-before-deploying
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: replace-before-deploying
