apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: bitloops
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 4173
      targetPort: 4173
  type: LoadBalancer